### ISSUE TITLE
Issue when installing from clean env

### ISSUE THREAD

**Issue by moemyself3** [moemyself3/lightcurator#7]
Here is a copy of issue.

```
  ----------------------------------------
  Failed building wheel for sep
  Running setup.py clean for sep
Failed to build sep
Installing collected packages: numpy, astropy, sep, toolz, dask, decorator, networkx, cloudpickle, scipy, pyparsing, six, python-dateutil, kiwisolver, cycler, matplotlib, pillow, PyWavelets, scikit-image, astroalign, photutils, lightcurator
  Running setup.py install for sep ... done
Successfully installed PyWavelets-1.0.2 astroalign-1.0.1 astropy-3.1.2 cloudpickle-0.8.0 cycler-0.10.0 dask-1.1.4 decorator-4.4.0 kiwisolver-1.0.1 lightcurator-1.0.0a0 matplotlib-3.0.3 networkx-2.2 numpy-1.16.2 photutils-0.6 pillow-5.4.1 pyparsing-2.3.1 python-dateutil-2.8.0 scikit-image-0.14.2 scipy-1.2.1 sep-1.0.3 six-1.12.0 toolz-0.9.0
```

**Comment by martinberoiz** [comment]
sep can fail installation from binaries (that's what wheel is) but it is installed successfully when done manually from setup.py.

It's in the list of installed packages at the end.

**Comment by moemyself3** [comment]
> sep can fail installation from binaries (that's what wheel is) but it is installed successfully when done manually from setup.py.
> 
> It's in the list of installed packages at the end.

So does that mean that this is not really an issue? I did notice it is in the list of things installed successfully when I ran pip install

**Comment by martinberoiz** [comment]
I don't think it is, but I would check that you can import the package with no problems after installing.
I would also check that the tests pass, but you don't have tests at the moment.

**Comment by moemyself3** [comment]
Importing was ultimately successful. I need to build tests.
